# Prueba 2: Caso Complejo
FROM ubuntu:22.04
# Actualizar el sistema e instalar dependencias
RUN apt-get update && \
    apt-get install -y python3 \
    python3-pip
ENV APP_HOME=/var/www/app \
    FLASK_ENV=production
ARG VERSION=1.0
WORKDIR $APP_HOME
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
# Exponer el puerto
EXPOSE 8080
CMD ["python3", "app.py"]
